Q1. An e-commerce store stores information about its products in a nested dictionary. The outer dictionary uses product IDs as keys, and the inner dictionary stores product details like name, category, price, and stock quantity. products = { 101: {"name": "Laptop", "category": "Electronics", "price": 1200, "stock": 50}, 102: {"name": "Shirt", "category": "Apparel", "price": 25, "stock": 200}, 103: {"name": "Coffee Maker", "category": "Home Appliances", "price": 80, "stock": 30} }

• Increase the stock of the "Shirt" product (add 50 more units) using increment/decrement operators

• Add a new product (e.g., "Smartphone")

Expected Output:

{101: {'name': 'Laptop', 'category': 'Electronics', 'price': 1200, 'stock': 50}, 102: {'name': 'Shirt', 'category': 'Apparel', 'price': 25, 'stock': 250}, 103: {'name': 'Coffee Maker', 'category': 'Home Appliances', 'price': 80, 'stock': 30}} {101: {'name': 'Laptop', 'category': 'Electronics', 'price': 1200, 'stock': 50}, 102: {'name': 'Shirt', 'category': 'Apparel', 'price': 25, 'stock': 250}, 103: {'name': 'Coffee Maker', 'category': 'Home Appliances', 'price': 80, 'stock': 30}, 104: {'name': 'Smartphone', 'category': 'Electronics', 'price': 800, 'stock': 100}}

In [ ]:
products = { 101: {"name": "Laptop", "category": "Electronics", "price": 1200, "stock": 50}, 102: {"name": "Shirt", "category": "Apparel", "price": 25, "stock": 200}, 103: {"name": "Coffee Maker", "category": "Home Appliances", "price": 80, "stock": 30} }

In [ ]:
products[102]['stock'] += 50

In [ ]:
products[104] ={'name': 'Smartphone', 'category': 'Electronics','price': 800, 'stock': 100}

In [ ]:
products

{101: {'name': 'Laptop',
  'category': 'Electronics',
  'price': 1200,
  'stock': 50},
 102: {'name': 'Shirt', 'category': 'Apparel', 'price': 25, 'stock': 250},
 103: {'name': 'Coffee Maker',
  'category': 'Home Appliances',
  'price': 80,
  'stock': 30},
 0: None,
 104: {'name': 'Smartphone',
  'category': 'Electronics',
  'price': 800,
  'stock': 100}}

Q2. You are given a list that contains some duplicate items. Remove the duplicates by converting the list to a set. Final output should be in list

shopping_list = ["apple", "banana", "apple", "orange", "banana", "grape"]

Expected Output: ['apple', 'grape', 'banana', 'orange']

In [ ]:
shopping_list = ["apple", "banana", "apple", "orange", "banana", "grape"]

In [ ]:
shopping_list

['apple', 'banana', 'apple', 'orange', 'banana', 'grape']

In [ ]:
#shopping_list.remove('banana')

In [ ]:
setlist=set(shopping_list)

In [ ]:
dir(set)

['__and__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iand__',
 '__init__',
 '__init_subclass__',
 '__ior__',
 '__isub__',
 '__iter__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__or__',
 '__rand__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__ror__',
 '__rsub__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__xor__',
 'add',
 'clear',
 'copy',
 'difference',
 'difference_update',
 'discard',
 'intersection',
 'intersection_update',
 'isdisjoint',
 'issubset',
 'issuperset',
 'pop',
 'remove',
 'symmetric_difference',
 'symmetric_difference_update',
 'union',
 'update']

In [ ]:
setlist

{'apple', 'banana', 'grape', 'orange'}

In [ ]:
list(setlist)

['apple', 'orange', 'grape', 'banana']

Q3. You are managing a list of students enrolled in two different courses. You need to perform various set operations to understand the student enrollment. Task: Create two sets: one for students in "Course A" and one for students in "Course B". Find the students who are in "Course A" but not in "Course B" (difference). Find students who are only in one of the two courses (symmetric difference). course_a = {"John", "Alice", "Bob", "David"} course_b = {"Alice", "Eve", "Charlie", "David"}

Using set methods

• Find students who are in Course A but not in Course B (difference)

• Find students who are only in one of the two courses (symmetric difference)

Expected Output:

Students in Course A but not in Course B: {'Bob', 'John'}

Students only in one of the two courses: {'Eve', 'John', 'Bob', 'Charlie'}

In [ ]:
course_a = {"John", "Alice", "Bob", "David"}

In [ ]:
course_b = {"Alice", "Eve", "Charlie", "David"}

Find students who are in Course A but not in Course B (difference)

In [ ]:
dir(set)

['__and__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iand__',
 '__init__',
 '__init_subclass__',
 '__ior__',
 '__isub__',
 '__iter__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__or__',
 '__rand__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__ror__',
 '__rsub__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__xor__',
 'add',
 'clear',
 'copy',
 'difference',
 'difference_update',
 'discard',
 'intersection',
 'intersection_update',
 'isdisjoint',
 'issubset',
 'issuperset',
 'pop',
 'remove',
 'symmetric_difference',
 'symmetric_difference_update',
 'union',
 'update']

In [ ]:
course_a.difference(course_b)

{'Bob', 'John'}

• Find students who are only in one of the two courses (symmetric difference)

In [ ]:
course_a.symmetric_difference(course_b)

{'Bob', 'Charlie', 'Eve', 'John'}

Q4. Write a Python program to store and display the details of a book.

The program should ask the user to input the following information:

Title of the book

Author’s name

Year of publication

Price of the booK

Store the entered details in a tuple.

Finally, display the book details in a proper format as shown below:

Expected Output:

Title: Harry Potter

Author: JK Rowlings

Year of Publication: 2000

Price: $180.0

In [ ]:
titleinp = input('Enter the title of the book')
authorinp = input('Enter the author of the book')
yearpubinp = input('Enter the year of publication of the book')
priceinp = input('Enter the price of the book')

#bookInfoStore = ({'Title':titleinp,'Author':authorinp,'Year of Publication':yearpubinp,'Price':priceinp})
bookInfoStore = (titleinp,authorinp,yearpubinp,priceinp)
output = f"""Title: {bookInfoStore[0]}
Author:{bookInfoStore[1]}
Year of Publication:{bookInfoStore[2]}
Price:{bookInfoStore[3]}"""
print(output)

Enter the title of the bookXyz
Enter the author of the bookZz
Enter the year of publication of the book2025
Enter the price of the book500
Title: Xyz
Author:Zz
Year of Publication:2025
Price:500

Q5. Write a program to check if a user’s chosen subject is available in the list of offered subjects.

Instructions:

Given a list of subjects, ask the user to input a subject.

Display whether the subject is available or not.

Expected Output:

Enter the subject you are interested in: art

art is available.

In [ ]:
subjectlist = ["Math", "English", "Physics", "Chemistry", "Biology", "Computer Science"]
userInp = input("enter a subjectname")
if userInp in subjectlist:
       print(f"""{userInp} is available""")
else:
    print(f"""{userInp} is not available""")

enter a subjectnameMath
Math is available

Q6. Write a Python program that asks the user to enter a number.

If the number is greater than 0, print "Positive".

If the number is less than 0, print "Negative".

If the number is exactly 0, print "Zero".

Expected Output:

Enter a number: 2

The number is Positive

Enter a number: 0

The number is Zero

Enter a number: -1

The number is Negative

In [ ]:

userInp = int(input("please enter a number"))

if userInp > 0:
  print("The number is Positive")
elif userInp < 0:
  print("The number is Negative")
elif userInp == 0 and userInp < 1:
  print("The number is Zero")

please enter a number-2
The number is Negative

Q7. Write a Python program that simulates a simple login system.

The correct username is 'admin' and the correct password is 'admin@123'

The program should take username and password as input from the user.

It should check the input and display messages according to the following conditions:

If both username and password are correct → print "Login Successful".

If username is wrong but password is correct → print "Invalid Username".

If username is correct but password is wrong → print "Invalid Password".

If both username and password are wrong → print "Invalid Username and Password".

In [46]:
 inpName = input("please enter a username")
inpPass = input("please enter a password")
username = 'admin'
userpass =  'admin@123'

if inpName == username and inpPass == userpass:
  print("Login Successful")
elif inpName == username or (inpPass == userpass and inpName== username):
  print( "Invalid Password")
elif inpPass == userpass or (inpPass == userpass and inpName== username):
  print( "Invalid Username")
else:
  print("Invalid Username and Password")

please enter a usernameadmin
please enter a passwordadmin@123
Login Successful

Q8.

student_details = { "Ali": {"age": 20, "grade": "A", "city": "Karachi"}, "Sara": {"age": 21, "grade": "B", "city": "Lahore"}, "Omar": {"age": 19, "grade": "A", "city": "Islamabad"}, "Hina": {"age": 22, "grade": "C", "city": "Faisalabad"} }

Add a new student using method: "Zara": {"age": 20, "grade": "B", "city": "Multan"}

Remove a student "Omer" using method

Expected Output:

{'Ali': {'age': 20, 'grade': 'A', 'city': 'Karachi'}, 'Sara': {'age': 21, 'grade': 'B', 'city': 'Lahore'}, 'Hina': {'age': 22, 'grade': 'C', 'city': 'Faisalabad'}, 'Zara': {'age': 20, 'grade': 'B', 'city': 'Multan'}}

In [1]:
student_details = { "Ali": {"age": 20, "grade": "A", "city": "Karachi"}, "Sara": {"age": 21, "grade": "B", "city": "Lahore"}, "Omar": {"age": 19, "grade": "A", "city": "Islamabad"}, "Hina": {"age": 22, "grade": "C", "city": "Faisalabad"} }

In [2]:
dir({})

['__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__ior__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__or__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__ror__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'clear',
 'copy',
 'fromkeys',
 'get',
 'items',
 'keys',
 'pop',
 'popitem',
 'setdefault',
 'update',
 'values']

In [13]:
student_details.setdefault('shayan',{"age": 20, "grade": "B", "city": "Multan"})

{'age': 20, 'grade': 'B', 'city': 'Multan'}

In [14]:
student_details

{'Ali': {'age': 20, 'grade': 'A', 'city': 'Karachi'},
 'Sara': {'age': 21, 'grade': 'B', 'city': 'Lahore'},
 'Omar': {'age': 19, 'grade': 'A', 'city': 'Islamabad'},
 'Hina': {'age': 22, 'grade': 'C', 'city': 'Faisalabad'},
 'Zara': None,
 'shayan': {'age': 20, 'grade': 'B', 'city': 'Multan'}}

In [15]:
student_details.pop("Omar")

{'age': 19, 'grade': 'A', 'city': 'Islamabad'}

In [16]:
student_details

{'Ali': {'age': 20, 'grade': 'A', 'city': 'Karachi'},
 'Sara': {'age': 21, 'grade': 'B', 'city': 'Lahore'},
 'Hina': {'age': 22, 'grade': 'C', 'city': 'Faisalabad'},
 'Zara': None,
 'shayan': {'age': 20, 'grade': 'B', 'city': 'Multan'}}

Q9. Write program to check a person’s eligibility for a loan based on age, credit score, and income. This time, the eligibility criteria will be:

The person must be 18 years or older. The person must have a credit score of 650 or higher. The person must have an annual income of at least 30000 dollars If the person has a credit score of 700 or higher, they may still be eligible with an income of 25000 dollars or more.

Expected Output:

Enter your age: 22

Enter your credit score: 888

Enter your annual income: $ 800000

You are eligible for the loan!

Enter your age: 15

Enter your credit score: 800

Enter your annual income: $ 900000

You are not eligible for the loan due to age.

Enter your age: 35

Enter your credit score: 99

Enter your annual income: $ 900000

You are not eligible for the loan due to low credit score.

In [28]:

age = int(input("please enter a age"))
creditscore = int(input("please enter a creditscore"))
inalincome = int(input("please enter a annual income"))

if age >= 18 and creditscore >=650 and inalincome >=30000:
  print(f"""your age: {age}
your credit score: {creditscore}
your annual income: {inalincome}
You are eligible for the loan""")


elif age < 18 or (creditscore >=650 and inalincome >=30000):
   print(f"""your age: {age}
your credit score: {creditscore}
your annual income: {inalincome}
You are not eligible for the loan due to age""")

elif age >= 18 or (creditscore < 650 and inalincome >=30000):
  print(f"""your age: {age}
your credit score: {creditscore}
your annual income: {inalincome}
You are not eligible for the loan due to creditscore""")

please enter a age22
please enter a creditscore800
please enter a annual income45000
your age: 22
your credit score: 800
your annual income: 45000
You are eligible for the loan

Q10. Write a Python program to check whether the entered letter is a vowel, a consonant, or invalid input.

The program should take a single character as input. If the character is a vowel (a, e, i, o, u in both upper and lower case), it will print "Vowel". If it is an alphabet but not a vowel, it will print "Consonant". Otherwise, it will print "Please enter valid alphabet".

Expected Output:

Enter a single letter: a

a is a Vowel

Enter a single letter: E

E is a Vowel

Enter a single letter: z

z is a Consonant

Enter a single letter: 7

Please enter valid alphabet

In [39]:
vowelstr = input("please enter a single character")

if vowelstr == "a":
  print(f"""Enter a single letter:{vowelstr}
{vowelstr} is a Vowel""")
elif vowelstr == "e":
  print(f"""Enter a single letter:{vowelstr}
{vowelstr} is a Vowel""")
elif vowelstr == "o":
  print(f"""Enter a single letter:{vowelstr}
{vowelstr} is a Vowel""")
elif vowelstr == "i":
  print(f"""Enter a single letter:{vowelstr}
{vowelstr} is a Vowel""")
elif vowelstr == "u":
  print(f"""Enter a single letter:{vowelstr}
{vowelstr} is a Vowel""")
elif vowelstr or  "bcdfghjklmnpqrstvwxyz":
  print(f"""Enter a single letter:{vowelstr}
{vowelstr} is a Constant""")
else:
  print("Please enter valid alphabet")

please enter a single characterq
Enter a single letter:q
q is a Constant